services:
  nftables-gui:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - no-new-privileges:true
    environment:
      NFT_GUI_USER: ${NFT_GUI_USER:-admin}
      NFT_GUI_PASS: ${NFT_GUI_PASS:-troque-isto}
      FLASK_ENV: production
    restart: unless-stopped

  nft-proxy:
    image: nginx:alpine
    container_name: nft-proxy
    depends_on:
      - nftables-gui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nftables.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  proxy:
    external: true
    name: dokploy-network
