services:
  nftables-gui:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - no-new-privileges:true
    environment:
      NFT_GUI_USER: ${NFT_GUI_USER:-admin}
      NFT_GUI_PASS: ${NFT_GUI_PASS:-troque-isto}
      FLASK_ENV: production
    restart: unless-stopped

  nft-proxy:
    image: nginx:alpine
    depends_on:
      - nftables-gui
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: dokploy-network
