version: "3.8"

services:
  nftables-gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nftables-gui
    restart: unless-stopped
    # Publica 8080 no host -> 8000 no container (porta do Gunicorn)
    ports:
      - "8080:8000"
    # Se sua app precisa de capabilities para manipular nftables no host,
    # comente/descomente conforme seu ambiente:
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /etc/nftables.conf:/etc/nftables.conf
      - /etc/nftables:/etc/nftables
    environment:
      # Ajuste conforme seu setup
      - GUNICORN_WORKERS=2
      - GUNICORN_TIMEOUT=120
