services:
  nftables-gui:
    build: .
    # Porta interna deve bater com o -b do gunicorn
    expose:
      - "8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/usr/lib/python3/dist-packages
    # Se o container vai manipular nftables do host, dê capacidades
    cap_add:
      - NET_ADMIN
    # Se precisar do /etc/nftables.conf do host, monte como volume (opcional)
    # volumes:
    #   - /etc/nftables.conf:/etc/nftables.conf:rw

  nft-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - nftables-gui
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
