version: "3.8"

services:
  nftables-gui:
    build:
      context: .
    container_name: nftables-gui
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - GUNICORN_WORKERS=2
      - GUNICORN_TIMEOUT=120
    # labels de roteamento (exemplo Traefik) — ajuste para sua plataforma
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.nftables-gui.rule=Host(`seu-dominio.com`)"
    #   - "traefik.http.services.nftables-gui.loadbalancer.server.port=8000"
